# Generated by Django 5.2.16 on 2026-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
