# Generated by Django 5.2.16 on 2026-07-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alert_risk_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FogHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_name', models.CharField(max_length=100)),
                ('health_score', models.FloatField()),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('average_speed', models.FloatField(default=0)),
                ('average_temperature', models.FloatField(default=0)),
                ('average_vibration', models.FloatField(default=0)),
                ('average_passenger', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
